server:
  port: 8001
spring:
  application:
    name: cluod-provider-hystrix-payment8001
eureka:
  client:
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7002.com:7001/eureka/
    register-with-eureka: true
    fetch-registry: true
